- PrebidMobile/DemoApp/build.gradle
- PrebidMobile/DemoApp/src/main/AndroidManifest.xml
- PrebidMobile/DemoApp/src/main/java/org/prebid/mobile/demoapp/Constants.java
- PrebidMobile/DemoApp/src/main/java/org/prebid/mobile/demoapp/DemoActivity.java
- PrebidMobile/DemoApp/src/main/java/org/prebid/mobile/demoapp/FormatChoiceActivity.java
- PrebidMobile/DemoApp/src/main/java/org/prebid/mobile/demoapp/MainActivity.java
- PrebidMobile/DemoApp/src/main/java/org/prebid/mobile/demoapp/PrebidApplication.java
- PrebidMobile/DemoApp/src/main/java/org/prebid/mobile/demoapp/dfpdemofragments/DFPInterstitialFragment.java
- PrebidMobile/DemoApp/src/main/java/org/prebid/mobile/demoapp/mopubdemofragments/MoPubBannerFragment.java
- PrebidMobile/DemoApp/src/main/java/org/prebid/mobile/demoapp/mopubdemofragments/MoPubInterstitialFragment.java
- Add MoPub Banner Fragment
- Add MoPub Interstitial Fragment
TODO: Add all Xamarin tests to the demo app and run them on Travis CI.
> Add Mopub to Demo App

- PrebidMobile/DemoApp/src/main/java/org/prebid/mobile/demoapp/Constants.java
- PrebidMobile/DemoApp/src/main/java/org/prebid/mobile/demoapp/PrebidApplication.java
- PrebidMobile/DemoApp/src/main/java/org/prebid/mobile/demoapp/dfpdemofragments/DFPBannerFragment.java
- PrebidMobile/DemoApp/src/main/java/org/prebid/mobile/demoapp/mopubdemofragments/MoPubBannerFragment.java
- PrebidMobile/DemoApp/src/main/java/org/prebid/mobile/demoapp/mopubdemofragments/MoPubInterstitialFragment.java
This PR includes minor changes to the demo app, like IDs for ad units, added Banner with wait for MoPub
> MoPub Demo App update

- PrebidMobile/PrebidServerAdapter/src/main/java/org/prebid/mobile/prebidserver/PrebidServerAdapter.java
- PrebidMobile/PrebidServerAdapter/src/main/java/org/prebid/mobile/prebidserver/internal/Settings.java
This PR includes adding several fields for request params to compliant ORTB.
> Update params per ORTB

- Maven/deployprebidmobile.sh
- Maven/pom.xml
- PrebidMobile/DemoApp/build.gradle
- PrebidMobile/DemoApp/src/main/java/org/prebid/mobile/demoapp/Constants.java
- PrebidMobile/PrebidMobileCore/src/main/java/org/prebid/mobile/core/LogUtil.java
- PrebidMobile/build.gradle
- README.md
- buildprebid.sh
This PR includes version updates in the project.
> Release 0.0.2

- PrebidMobile/DemoApp/src/main/AndroidManifest.xml
- buildprebid.sh
Addresses https://github.com/prebid/prebid-mobile-android/issues/5
> Fix MoPub build errors

- Maven/pom.xml
- PrebidMobile/IntegrationTests/features/step_definitions/calabash_steps.rb
- PrebidMobile/PrebidServerAdapter/src/main/java/org/prebid/mobile/prebidserver/internal/Settings.java
- PrebidMobile/build.gradle
- README.md
This PR includes bumping version to 0.1.0.
> Update version to 0.1.0

- PrebidMobile/DemoApp/src/main/java/org/prebid/mobile/demoapp/MainActivity.java
- PrebidMobile/DemoApp/src/main/java/org/prebid/mobile/demoapp/PrebidApplication.java
- PrebidMobile/PrebidMobileCore/build.gradle
- PrebidMobile/PrebidMobileCore/src/main/java/org/prebid/mobile/core/BidManager.java
- PrebidMobile/PrebidMobileCore/src/main/java/org/prebid/mobile/core/CacheManager.java
- PrebidMobile/PrebidMobileCore/src/main/java/org/prebid/mobile/core/Prebid.java
- PrebidMobile/PrebidServerAdapter/src/main/java/org/prebid/mobile/prebidserver/PrebidServerAdapter.java
- PrebidMobile/PrebidServerAdapter/src/main/java/org/prebid/mobile/prebidserver/internal/Settings.java
This PR inlcudes a cache manager that helps to cache bids into webview localStorage. Haven't fully tested because pbm.js has to be changed to read the cache data.
> Cache manager for SDK

- PrebidMobile/PrebidServerAdapter/src/main/java/org/prebid/mobile/prebidserver/internal/Settings.java
Update as current asyn method won't pass the data in first call.
> Update the UA method

- PrebidMobile/PrebidMobileCore/src/main/java/org/prebid/mobile/core/CacheManager.java
- PrebidMobile/PrebidServerAdapter/src/main/java/org/prebid/mobile/prebidserver/PrebidServerAdapter.java
https://github.com/prebid/prebid-mobile-android/issues/76
> remove hb_creative_loadtype

- PrebidMobile/API1.0/src/main/AndroidManifest.xml
- PrebidMobile/API1.0/src/main/java/org/prebid/mobile/AdUnit.java
- PrebidMobile/API1.0/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
- PrebidMobile/API1.0Demo/build.gradle
- PrebidMobile/API1.0Demo/src/main/java/org/prebid/mobile/app/DemoActivity.java
> [Rubicon Project] Result Codes is not matched

- PrebidMobile/API1.0/src/main/java/org/prebid/mobile/AdvertisingIDUtil.java
- PrebidMobile/API1.0/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
> Fixing android warnings

- PrebidMobile/API1.0/src/main/java/org/prebid/mobile/DemandAdapter.java
- PrebidMobile/API1.0/src/main/java/org/prebid/mobile/DemandFetcher.java
- PrebidMobile/API1.0/src/main/java/org/prebid/mobile/OnCompleteListener.java
- PrebidMobile/API1.0/src/main/java/org/prebid/mobile/PrebidMobile.java
- PrebidMobile/API1.0/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
- PrebidMobile/API1.0/src/test/java/org/prebid/mobile/DemandFetcherTest.java
- PrebidMobile/API1.0/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
- PrebidMobile/API1.0/src/test/java/org/prebid/mobile/ResultCodeTest.java
- while timer was changed by CountDownTimer 
- @MainThread and @WorkerThread annotations were added
- while timer was changed by CountDownTimer
- testMode was removed
- tests were adapted
> Code improvement

- PrebidMobile/API1.0/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
- PrebidMobile/API1.0/src/test/java/org/prebid/mobile/DemandFetcherTest.java
- PrebidMobile/API1.0/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
- PrebidMobile/API1.0/src/test/java/org/prebid/mobile/ResultCodeTest.java
- PrebidMobile/API1.0/src/test/java/org/prebid/mobile/testutils/MockPrebidServerResponses.java
- PrebidMobile/API1.0/src/test/resources/PrebidServerInvalidBidRubiconResponseWithoutCacheId.json
- PrebidMobile/API1.0/src/test/resources/PrebidServerNoBidFromRubiconResponse.json
- PrebidMobile/API1.0/src/test/resources/PrebidServerOneBidFromRubiconResponse.json
- PrebidMobile/API1.0Demo/src/androidTest/java/org/prebid/mobile/app/DFPBannerTest.java
- PrebidMobile/API1.0Demo/src/androidTest/java/org/prebid/mobile/app/ExtraTests.java
- PrebidMobile/API1.0Demo/src/androidTest/java/org/prebid/mobile/app/MoPubBannerTest.java
- PrebidMobile/API1.0Demo/src/androidTest/java/org/prebid/mobile/testutils/ViewMinSizeMatcher.java
- PrebidMobile/API1.0Demo/src/main/java/org/prebid/mobile/app/Constants.java
- PrebidMobile/API1.0Demo/src/main/java/org/prebid/mobile/app/DemoActivity.java
> Add RubiconProject account to tests

- PrebidMobile/API1.0/proguard-rules.pro
> 1.1.1 findPrebidCreativeSize function does not work with Compile error

- PrebidMobile/API1.0/src/main/java/org/prebid/mobile/Host.java
> Build Javadoc failed

- PrebidMobile/API1.0Demo/src/main/java/org/prebid/mobile/app/DemoActivity.java
GitHub issue #141 
The sample code was added. The caller functions were commented not to mix up a developer
> [DemoApp] Create feature samples v1.2

- Example/PrebidDemoJava/src/androidTest/java/org/prebid/mobile/app/DFPNativeTest.java
- Example/PrebidDemoJava/src/androidTest/java/org/prebid/mobile/app/MoPubNativeTest.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/Constants.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/DemoActivity.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/NativeDataAsset.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
- PrebidMobile/src/test/java/org/prebid/mobile/NativeAdUnitTest.java
- PrebidMobile/src/test/java/org/prebid/mobile/NativeAssetTest.java
- PrebidMobile/src/test/java/org/prebid/mobile/NativeEventTrackerTest.java
- PrebidMobile/src/test/java/org/prebid/mobile/NativeRequestParamsTest.java
- PrebidMobile/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
- PrebidMobile/src/test/java/org/prebid/mobile/RequestParamsTest.java
Added test cases of PrebidNative for bannerNative DFP & mopub.
> PrebidNative test cases

- Example/PrebidDemoJava/build.gradle
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/CustomApplication.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/DemoActivity.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/MainActivity.java
- Example/PrebidDemoJava/src/main/res/values/strings.xml
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/AdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/RequestParams.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/VideoAdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/VideoInterstitialAdUnit.java
- PrebidMobile/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
- PrebidMobile/src/test/java/org/prebid/mobile/RequestParamsTest.java
- PrebidMobile/src/test/java/org/prebid/mobile/VideoAdUnitTest.java
- PrebidMobile/src/test/java/org/prebid/mobile/VideoInterstitialAdUnitTest.java
- scripts/buildPrebidMobile.sh
GitHub issue #146
API
```Java
new VideoAdUnit("1001_test_video", 300, 250, VideoAdUnit.PlacementType.IN_BANNER);
new VideoInterstitialAdUnit("1001_test_video");
```
`VideoAdUnit` has next types:
```
IN_BANNER
IN_ARTICLE
IN_FEED
``` 
OpennRTB request:
``` XML
{
"imp": [{
"video": {
"w": 640,
"h": 480,
"startdelay": 0,
"protocols": [7],
"playbackmethod": [2],
"mimes": ["video/mp4"],
"placement": 2 <--2, 3, 4 for VideoAdUnit and 5 for VideoInterstitialAdUnit-->
},
}],
"ext": {
"prebid": {
"cache": {
"vastxml": {}
},
},
},
"instl": 1 <--Only for Interstitial-->
}
```
> Video format support (Out-of-the-box)

- Example/PrebidDemoJava/src/androidTest/java/org/prebid/mobile/app/ExtraTests.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/DemoActivity.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
Issue #101
`AdvertisingIDUtil.retrieveAndSetAAID();` and `PrebidServerSettings.update();` were moved to `setApplicationContext()`
> Initialise post data before the first request

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/StorageUtils.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/TargetingParams.java
- PrebidMobile/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
- PrebidMobile/src/test/java/org/prebid/mobile/StorageUtilsTest.java
- PrebidMobile/src/test/java/org/prebid/mobile/TargetingParamsTest.java
- tools/drprebid/src/main/java/org/prebid/mobile/drprebid/validation/DemandRequestBuilder.java
> TCFv2[172] was improved

- Example/PrebidDemoJava/build.gradle
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/DemoActivity.java
- Example/PrebidDemoJava/src/main/res/values/strings.xml
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/RewardedVideoAdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/Util.java
- PrebidMobile/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
- PrebidMobile/src/test/java/org/prebid/mobile/RewardedVideoAdUnitTest.java
- PrebidMobile/src/test/java/org/prebid/mobile/UtilTest.java
Issue https://github.com/prebid/prebid-mobile-ios/issues/261
API
``` Java
new RewardedVideoAdUnit("1001");
```
OpenRTB
``` JSON
{
"ext": {
"prebid": {
"cache": {
"vastxml": {},
},
}
},
"imp": [{
"video": {
"w": 414,
"h": 896,
"linearity": 1,
"mimes": ["video/mp4"],
"placement": 5,
"playbackmethod": [2]
},
"instl": 1,
"ext": {
"prebid": {
"is_rewarded_inventory": 1
}
},
}]
}
```
> Rewarded video support

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/Util.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/addendum/AdViewUtils.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/addendum/LimitedQueueContainer.java
- PrebidMobile/src/test/java/org/prebid/mobile/addendum/LimitedQueueContainerTest.java
Additional logic was added to handle zoom
This solution was tested on two different screen sizes with two different ad sizes.
Notes:
`webView.getSettings().setLoadWithOverviewMode(true);`  has unexpected behavior
> Ad is zoomed in after resizing

- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/DemoActivity.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
- PrebidMobile/src/test/java/org/prebid/mobile/PrebidMobileTest.java
- PrebidMobile/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
API
Java 
``` Java
PrebidMobile.setPbsDebug(true);
```
OpenRTB:
```JSON
{
"test":1,
...
}
```
> PBS Debug Mode

- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/DemoActivity.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/AdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/BannerAdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/BannerBaseAdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/InterstitialAdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/RequestParams.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/Signals.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/VideoBaseAdUnit.java
- PrebidMobile/src/test/java/org/prebid/mobile/AdUnitSuccessorTest.java
- PrebidMobile/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
- PrebidMobile/src/test/java/org/prebid/mobile/RequestParamsTest.java
`BannerAdUnit` and `InterstitialAdUnit` has `api` field
API:
``` Java
BannerAdUnit adUnit = new BannerAdUnit(configId, width, height);
BannerBaseAdUnit.Parameters parameters = new BannerBaseAdUnit.Parameters();
parameters.setApi(Arrays.asList(Signals.Api.MRAID_2));
//parameters.setApi(Arrays.asList(new Signals.Api(5)));
adUnit.setParameters(parameters);
```
OpenRTB:
```XML
"imp": [{
"banner": {
"api": [5]
}
}]
```
> Banner api frameworks field

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/TargetingParams.java
- PrebidMobile/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
- PrebidMobile/src/test/java/org/prebid/mobile/TargetingParamsTest.java
[GitHub issue](https://github.com/prebid/prebid-mobile-ios/issues/308)
API:
``` Java
TargetingParams.setOmidPartnerName("PartnerName");
TargetingParams.setOmidPartnerVersion("1.0");
```
JSON:
```
"source" {  
"ext": {  
"omidpn": "PartnerName",  
"omidpv": "1.0"  
}  
}
```
> OMSDK signaling support

- tools/drprebid/build.gradle
- tools/drprebid/src/main/java/org/prebid/mobile/drprebid/ui/activities/TestResultsActivity.java
- tools/drprebid/src/main/java/org/prebid/mobile/drprebid/ui/viewholders/AdServerValidationViewHolder.java
- tools/drprebid/src/main/java/org/prebid/mobile/drprebid/ui/viewholders/SdkValidationViewHolder.java
- tools/drprebid/src/main/java/org/prebid/mobile/drprebid/ui/viewmodels/AdServerValidationViewModel.java
- tools/drprebid/src/main/java/org/prebid/mobile/drprebid/ui/viewmodels/SdkValidationViewModel.java
- tools/drprebid/src/main/java/org/prebid/mobile/drprebid/validation/AdServerTest.java
- tools/drprebid/src/main/java/org/prebid/mobile/drprebid/validation/AdViewUtils.java
- tools/drprebid/src/main/java/org/prebid/mobile/drprebid/validation/SdkTest.java
- tools/drprebid/src/main/res/drawable/icon_not_supported.xml
- tools/drprebid/src/main/res/layout/view_ad_server_settings.xml
AdManager and interstitial format creative validation is not supported
> [Dr. Prebid] AdManager was added as AdServer

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/TargetingParams.java
* GDPR Purpose Consent and Consent String was preferred over TCF Purpose Consent and Consent String.
* Changed the order of preference to prefer TCF over GDPR
> Preferred TCF PurposeConsent anf TCF ConsentString over GDPR

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerSettings.java
- build.gradle
- scripts/Maven/PrebidMobile-core-pom.xml
Updated Prebid version to `1.10`
> Release branch (1.10)

- Example/PrebidDemoJava/build.gradle
- README.md
- scripts/Maven/PrebidMobile-pom.xml
* Updated version in PrebidMobile-pom.xml
> Release 1.10

- Example/PrebidDemoJava/build.gradle
- Example/PrebidDemoJava/src/androidTest/java/org/prebid/mobile/app/AdManagerComplexTest.java
- Example/PrebidDemoJava/src/androidTest/java/org/prebid/mobile/app/ExtraTests.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/RubiconBannerGamDemoActivity.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/RubiconBannerVideoGamDemoActivity.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/RubiconInterstitialGamDemoActivity.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/RubiconInterstitialVideoGamDemoActivity.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/RubiconRewardedVideoGamDemoActivity.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/XandrBannerGamDemoActivity.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/XandrInterstitialGamDemoActivity.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/XandrNativeInAppGAMDemoActivity.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/XandrNativeInAppMoPubDemoActivity.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/XandrNativeInBannerGamDemoActivity.java
- Example/PrebidDemoKotlin/build.gradle
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/DemoActivity.kt
- PrebidMobile/PrebidMobile-core/proguard-rules.pro
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/Util.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/addendum/AdViewUtils.java
- PrebidMobile/build.gradle
- PrebidMobile/gradle.properties
- PrebidMobile/src/test/java/org/prebid/mobile/DemandFetcherTest.java
- PrebidMobile/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
- PrebidMobile/src/test/java/org/prebid/mobile/ResultCodeTest.java
- PrebidMobile/src/test/java/org/prebid/mobile/UtilTest.java
- build.gradle
- tools/drprebid/src/main/java/org/prebid/mobile/drprebid/validation/AdServerTest.java
- tools/drprebid/src/main/java/org/prebid/mobile/drprebid/validation/SdkTest.java
PrebidSDK supports AdManager v20
PrebidSDK UnitTests, PrebidDemoJava, PrebidDemoKotlin migrated to AdManager v20
> Adapt Prebid SDK to AdManager v20.0.0 

- Example/PrebidDemoJava/build.gradle
- Example/PrebidDemoKotlin/build.gradle
- Example/PrebidDemoKotlin/src/androidTest/java/org/prebid/mobile/prebidkotlindemo/ExampleInstrumentedTest.kt
- Example/PrebidDemoKotlin/src/main/AndroidManifest.xml
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/CustomApplication.kt
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/DemoActivity.kt
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/MainActivity.kt
- Example/PrebidDemoKotlin/src/main/res/layout/activity_demo.xml
- Example/PrebidDemoKotlin/src/main/res/layout/activity_main.xml
- Example/PrebidDemoKotlin/src/main/res/values/strings.xml
- Example/PrebidDemoKotlin/src/test/java/org/prebid/mobile/prebidkotlindemo/ExampleUnitTest.kt
- PrebidMobile/PrebidMobile-gamEventHandlers/build.gradle
- PrebidMobile/PrebidMobile-mopubAdapters/build.gradle
- PrebidMobile/PrebidMobile-rendering/build.gradle
- PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/networking/BaseNetworkTask.java
- PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/utils/exposure/ViewExposureChecker.java
- PrebidMobile/PrebidMobile-rendering/src/test/java/org/prebid/mobile/rendering/networking/BaseNetworkTaskTest.java
- PrebidMobile/PrebidMobile-rendering/src/test/java/org/prebid/mobile/rendering/sdk/deviceData/managers/DeviceInfoImplTest.java
- PrebidMobile/build.gradle
- PrebidMobile/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
- PrebidMobile/src/test/java/org/prebid/mobile/testutils/BaseSetup.java
- build.gradle
- scripts/buildPrebidMobile.sh
- scripts/testPrebidMobile.sh
Updated build scripts for building with rendering module. 
Fully refactored PrebidDemoKotlin app.
Added in-app rendering banner for PrebidDemoKotlin app. 
Revived unit tests and updated tests dependencies. 
Updated testPrebidMobile script to run rendering modules too.
Unit tests state before:
Unit tests state now:
> Migration of rendering module and reviving unit tests. 

- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/Constants.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/XandrNativeInAppGAMDemoActivity.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/NativeRequestParams.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
* #271 
* Added the missing key (`id`) to the assets in the asset array.
> Issue #271 Ms 4877 - InApp Native Fix

- scripts/Maven/PrebidMobile-core-pom.xml
- scripts/Maven/PrebidMobile-pom.xml
* Updated prebid sdk version to 1.12.1
> Release branch (1.12.1)

- Example/PrebidDemoKotlin/build.gradle
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/CustomApplication.kt
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/DemoActivity.kt
- Example/PrebidDemoKotlin/src/main/res/values/strings.xml
- Example/PrebidInternalTestApp/build.gradle
- PrebidMobile/PrebidMobile-gamEventHandlers/build.gradle
- PrebidMobile/PrebidMobile-mopubAdapters/build.gradle
- PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/networking/BaseNetworkTask.java
- PrebidMobile/build.gradle
- build.gradle
PrebidKotlinDemo and PrebidInternalTestsApp now implements PrebidSDK (with rendering). MoPub adapters and GAM event handlers are included in separated modules. Added InApp with GAM test to PrebidKotlinDemo app. 
#276
> Changing project structure, adding In-App with GAM example to KotlinDemo. 

- PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/bidding/data/bid/ContentObject.java
- PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/bidding/display/MediationBaseAdUnit.java
- PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/bidding/parallel/BannerView.java
- PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/bidding/parallel/BaseInterstitialAdUnit.java
- PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/App.java
- PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/networking/modelcontrollers/Requester.java
- PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/networking/parameters/AppInfoParameterBuilder.java
- PrebidMobile/PrebidMobile-rendering/src/test/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/AppTest.java
- PrebidMobile/PrebidMobile-rendering/src/test/java/org/prebid/mobile/rendering/networking/parameters/AppInfoParameterBuilderTest.java
- PrebidMobile/PrebidMobile-rendering/src/test/java/org/prebid/mobile/rendering/networking/urlBuilder/AutoDetectedOpenRtbTest.java
Added content object to BannerView, MediationBaseAdUnit, BaseInterstitialAdUnit. Corrected tests to work with content url. #300
> Added content url field onto rendering API 

- PrebidMobile/PrebidMobile-gamEventHandlers/src/main/java/org/prebid/mobile/eventhandlers/utils/GamUtils.java
- PrebidMobile/PrebidMobile-gamEventHandlers/src/test/java/org/prebid/mobile/eventhandlers/utils/GamUtilsTest.java
- PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/bidding/data/NativeFetchDemandResult.java
- PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/bidding/display/NativeAdUnit.java
- PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/bidding/parallel/BannerView.java
- PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/bidding/parallel/BaseInterstitialAdUnit.java
- PrebidMobile/PrebidMobile-rendering/src/test/java/org/prebid/mobile/rendering/bidding/display/NativeAdUnitTest.java
- PrebidMobile/PrebidMobile-rendering/src/test/java/org/prebid/mobile/rendering/bidding/parallel/BannerViewTest.java
- PrebidMobile/PrebidMobile-rendering/src/test/java/org/prebid/mobile/rendering/bidding/parallel/BaseInterstitialAdUnitTest.java
- PrebidMobile/PrebidMobile-rendering/src/test/java/org/prebid/mobile/rendering/utils/ntv/NativeUtilsTest.java
Bid response is public in BannerView and BaseInterstitialAdUnit. Added bid response to NativeFetchDemandResult. Corrected and added test cases. #297
> Public bid response 

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerSettings.java
- build.gradle
- scripts/Maven/PrebidMobile-core-pom.xml
- scripts/Maven/PrebidMobile-open-measurement-pom.xml
- scripts/Maven/PrebidMobile-pom.xml
- scripts/Maven/PrebidMobile-rendering-pom.xml
- scripts/Maven/deployPrebidMobile.sh
Updated release version to 1.13-beta1. Updated deploy scripts and added pom files for deploying the rendering part. #303
> Added deploying of rendering part and updated release version

- PrebidMobile/PrebidMobile-gamEventHandlers/build.gradle
- scripts/Maven/PrebidMobile-core-pom.xml
- scripts/Maven/PrebidMobile-gamEventHandlers-pom.xml
- scripts/Maven/PrebidMobile-mopubAdapters-pom.xml
- scripts/Maven/PrebidMobile-open-measurement-pom.xml
- scripts/Maven/PrebidMobile-pom.xml
- scripts/Maven/PrebidMobile-rendering-pom.xml
- scripts/Maven/deployPrebidMobile.sh
- scripts/buildPrebidMobile.sh
Gam event handlers and Mopub adapters build and deploy with global scripts. Added pom files for deploying.
> Added ability to deploy handlers and adapters

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/DemandFetcher.java
Add check for destroyed fetchers. #268
> Fix stop method in DemandFetcher

- Example/PrebidDemoJava/build.gradle
- Example/PrebidDemoKotlin/build.gradle
- Example/PrebidInternalTestApp/build.gradle
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerSettings.java
- PrebidMobile/PrebidMobile-rendering/build.gradle
- build.gradle
- scripts/Maven/PrebidMobile-core-pom.xml
- scripts/Maven/PrebidMobile-gamEventHandlers-pom.xml
- scripts/Maven/PrebidMobile-mopubAdapters-pom.xml
- scripts/Maven/PrebidMobile-pom.xml
- scripts/Maven/PrebidMobile-rendering-pom.xml
> Replaced jcenter dependencies

- PrebidMobile/PrebidMobile-rendering/src/main/AndroidManifest.xml
Removed allow backup tag from manifest in rendering module. #316
> Manifest merge fix

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/DemandFetcher.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/http/HTTPPost.java
Added high priority for Demand handler to work in time. Fixed problem with double demand. #291
> Fixed timeout problem

- README.md
Range version can upload unstable releases, it's better to set up the exact version.
> Remove range version in readme file

- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/admob/AdMobInterstitialFragment.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/admob/AdMobRewardedFragment.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/utils/DemoItemProvider.kt
- PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/bidding/display/MediationInterstitialAdUnit.java
Add additional parameters. Fix AdMob examples. Closes #352.
> Minor corrections for AdMob

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/http/HTTPPost.java
- PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/networking/BaseNetworkTask.java
- PrebidMobile/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
This PR contains a fix for the problem reported in issue #319
> Handled response code 204 (BLANK), now returns NO_BID.

- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/AdTypesRepository.kt
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/CustomApplication.kt
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/DemoActivity.kt
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/AdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/BannerAdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/BannerBaseAdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/InterstitialAdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/NativeAdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/NativeAsset.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/NativeDataAsset.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/NativeImageAsset.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/NativeTitleAsset.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/RewardedVideoAdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/Util.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/VideoAdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/VideoBaseAdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/VideoInterstitialAdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/data/bid/Bid.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/data/bid/BidResponse.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/display/BidResponseCache.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/models/openrtb/BidRequest.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/Imp.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/Native.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilder.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/units/configuration/AdUnitConfiguration.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/units/configuration/NativeAdUnitConfiguration.java
Apply bid loader. Create methods for the auto-refresh interval in seconds. Add "test" field to request in rendering.
> Apply bid loader from rendering instead of demand fetcher

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/Host.java
- tools/drprebid/src/main/java/org/prebid/mobile/drprebid/Constants.java
Updated the Xandr endpoint to `https://ib.adnxs.com/openrtb2/prebid`
> Updated endpoint for Xandr requests

- .gitignore
- Example/PrebidDemoKotlin/build.gradle
- Example/PrebidDemoKotlin/src/main/AndroidManifest.xml
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/AdTypesRepository.kt
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/CustomApplication.kt
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/ads/inappmax/InAppMaxBanner.kt
- Example/PrebidDemoKotlin/src/main/res/values-sw600dp/attrs.xml
- Example/PrebidDemoKotlin/src/main/res/values/attrs.xml
- Example/PrebidInternalTestApp/build.gradle
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/data/DemoItem.kt
- Example/PrebidInternalTestApp/src/main/res/values/arrays.xml
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/ParametersMatcher.java
- PrebidMobile/PrebidMobile-maxAdapters/build.gradle
- PrebidMobile/PrebidMobile-maxAdapters/src/main/AndroidManifest.xml
- PrebidMobile/PrebidMobile-maxAdapters/src/main/java/com/applovin/mediation/adapters/MaxBannerMediationUtils.java
- PrebidMobile/PrebidMobile-maxAdapters/src/main/java/com/applovin/mediation/adapters/PrebidMAXMediationAdapter.java
- build.gradle
- scripts/Maven/PrebidMobile-maxAdapters-pom.xml
- scripts/Maven/deployPrebidMobile.sh
- scripts/buildPrebidMobile.sh
- scripts/testPrebidMobile.sh
- settings.gradle
Configure max adapters module. Create a banner adapter. Add an example to Kotlin app.
> Create Applovin Max banner adapter and configure environment 

- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/AdTypesRepository.kt
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/ads/inappmax/InAppMaxBanner.kt
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/ads/inappmax/InAppMaxInterstitial.kt
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/ads/inappmax/InAppMaxRewarded.kt
- PrebidMobile/PrebidMobile-maxAdapters/src/main/java/com/applovin/mediation/adapters/ListenersCreator.java
- PrebidMobile/PrebidMobile-maxAdapters/src/main/java/com/applovin/mediation/adapters/MaxInterstitialMediationUtils.java
- PrebidMobile/PrebidMobile-maxAdapters/src/main/java/com/applovin/mediation/adapters/MaxRewardedMediationUtils.java
- PrebidMobile/PrebidMobile-maxAdapters/src/main/java/com/applovin/mediation/adapters/ParametersChecker.java
- PrebidMobile/PrebidMobile-maxAdapters/src/main/java/com/applovin/mediation/adapters/PrebidMAXMediationAdapter.java
Create adapters. Change architecture. Move listeners to separate files.
> Create interstitial and rewarded MAX adapters

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/AdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/Signals.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/imps/Video.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilder.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/units/configuration/AdUnitConfiguration.java
Add Parameters support for original ad units in merged bid requester. Closes #408.
> Return original banner and video parameters support #408

- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/javademo/ads/AdTypesRepository.java
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/admob/AdMobInterstitialMultiformatFragment.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/gam/GamInterstitialMultiformatFragment.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/max/MaxBannerFragmentAdaptive.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/max/MaxInterstitialFragment.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/max/MaxInterstitialFragmentRandom.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/max/MaxRewardedFragment.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/max/MaxRewardedFragmentRandom.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/ppm/PpmInterstitialMultiformatFragment.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/utils/DemoItemProvider.kt
- Example/PrebidInternalTestApp/src/main/res/layout/fragment_bidding_banner_applovin_max.xml
- Example/PrebidInternalTestApp/src/main/res/navigation/bidding_navigation.xml
- Example/PrebidInternalTestApp/src/main/res/values/strings.xml
Add "OK, Adapter" and "OK, Random" examples.
> Add Applovin MAX examples 

- Example/PrebidDemoJava/build.gradle
- Example/PrebidDemoKotlin/build.gradle
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/ads/inapp/InAppVideoBanner.kt
- Example/PrebidInternalTestApp/build.gradle
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/admob/AdMobInterstitialMultiformatFragment.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/gam/GamInterstitialMultiformatFragment.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/max/MaxBannerFragmentAdaptive.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/max/MaxInterstitialFragmentMultiformat.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/ppm/PpmInterstitialMultiformatFragment.kt
- build.gradle
- scripts/Maven/PrebidMobile-admobAdapters-pom.xml
- scripts/Maven/PrebidMobile-core-pom.xml
- scripts/Maven/PrebidMobile-gamEventHandlers-pom.xml
- scripts/Maven/PrebidMobile-maxAdapters-pom.xml
- scripts/Maven/PrebidMobile-pom.xml
- scripts/buildPrebidMobile.sh
Update SDK version. Fix Applovin MAX adapters module release error. Some fixes.
> Preparation for release

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidNativeAd.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/mraid/methods/MraidController.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/mraid/methods/MraidPlayVideo.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/mraid/methods/MraidResize.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/sdk/calendar/CalendarGTE14.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/sdk/calendar/CalendarLT14.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/sdk/deviceData/managers/DeviceInfoImpl.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/sdk/deviceData/managers/DeviceInfoManager.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/sdk/deviceData/managers/UserConsentManager.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/utils/exposure/ViewExposureChecker.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/utils/helpers/ExternalViewerUtils.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/utils/helpers/VisibilityChecker.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/utils/url/action/MraidInternalBrowserAction.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/views/browser/BrowserControls.java
- PrebidMobile/PrebidMobile-core/src/main/res/raw/mraid.js
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/sdk/deviceData/managers/DeviceInfoImplTest.java
- tools/drprebid/src/main/java/org/prebid/mobile/drprebid/validation/SdkTest.java
Fix offscreen resizing. Make the close button position flexible for cases when it's moved out of the screen because of offset. Closes #288.
> Fix MRAID offscreen resize method #288

- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/AdFragment.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/utils/DemoItemProvider.kt
- Example/PrebidInternalTestApp/src/main/res/values/strings.xml
- PrebidMobile/PrebidMobile-admobAdapters/src/main/java/org/prebid/mobile/admob/PrebidNativeAdapter.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidNativeAd.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/rendering/DisplayView.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/configuration/AdUnitConfiguration.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/data/bid/BidResponse.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/data/bid/Prebid.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/display/InterstitialController.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/events/EventsNotifier.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/loading/CreativeFactory.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/models/CreativeModel.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/WinNotifier.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/utils/ntv/NativeAdProvider.java
- PrebidMobile/PrebidMobile-maxAdapters/src/main/java/com/applovin/mediation/adapters/prebid/managers/MaxNativeManager.java
Support "imp" and "win" events. Closes #443.
> Support events in rendering API 

- PrebidMobile/PrebidMobile-maxAdapters/src/main/java/com/applovin/mediation/adapters/PrebidMaxMediationAdapter.java
Set COPPA consent from MAX parameters. Closes #454.
> Applovin MAX privacy settings

- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/utils/DemoItemProvider.kt
- Example/PrebidInternalTestApp/src/main/res/values/strings.xml
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/interstitial/AdBaseDialog.java
Add more examples with ad configuration in bid response. Fix close button rendering settings. Closes #445.
> Rendering controls corrections

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/parameters/GeoLocationParameterBuilder.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/networking/parameters/GeoLocationParameterBuilderTest.java
We've fixed the issue mentioned in #483.
> ShareGeoLocation issue fix

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/parameters/GeoLocationParameterBuilder.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/utils/url/action/MraidInternalBrowserAction.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/networking/parameters/GeoLocationParameterBuilderTest.java
Fix isShareGeoLocation not checked.
> Geolocation fixes merge

- Example/PrebidDemoJava/build.gradle
- Example/PrebidDemoKotlin/build.gradle
- Example/PrebidInternalTestApp/build.gradle
- build.gradle
- scripts/Maven/PrebidMobile-admobAdapters-pom.xml
- scripts/Maven/PrebidMobile-core-pom.xml
- scripts/Maven/PrebidMobile-gamEventHandlers-pom.xml
- scripts/Maven/PrebidMobile-maxAdapters-pom.xml
- scripts/Maven/PrebidMobile-pom.xml
Return flag for new task in browser actions.
> Update release version to 2.0.3

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/parameters/AppInfoParameterBuilder.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/networking/parameters/AppInfoParameterBuilderTest.java
* Fixed issue with domain key missed in the app object
* This PR contains a fix for the issue mentioned in #495
> [#495] domain key missing in the app object

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/TargetingParams.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/parameters/UserConsentParameterBuilder.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/sdk/UserConsentUtils.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/sdk/deviceData/managers/UserConsentManager.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/TargetingParamsTest.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/reflection/sdk/UserConsentManagerReflection.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/networking/parameters/UserConsentParameterBuilderTest.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/sdk/UserConsentUtilsTest.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/sdk/deviceData/managers/UserConsentManagerTest.java
Correct consents. Fix tests. Save prebid values to static fields.
Closes #519.
> Consents improvements

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/data/FetchDemandResult.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/data/bid/BidResponse.java
> Fix SERVER_ERROR when NO_BIDS #521

- build.gradle
- scripts/Maven/PrebidMobile-admobAdapters-pom.xml
- scripts/Maven/PrebidMobile-core-pom.xml
- scripts/Maven/PrebidMobile-gamEventHandlers-pom.xml
- scripts/Maven/PrebidMobile-maxAdapters-pom.xml
- scripts/Maven/PrebidMobile-pom.xml
> Update version to 2.0.5

- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/javademo/testcases/IntegrationKind.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/javademo/utils/Settings.java
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/testcases/IntegrationKind.kt
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/utils/Settings.kt
> Set GAM Original api as default integration kind 

- Example/PrebidDemoKotlin/src/main/AndroidManifest.xml
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/activities/ads/gam/original/GamOriginalApiVideoBannerActivity.kt
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/testcases/TestCaseRepository.kt
- Example/PrebidDemoKotlin/src/main/res/values/strings.xml
> Add video banner example in Kotlin app

- Example/PrebidDemoJava/build.gradle
- Example/PrebidDemoKotlin/build.gradle
- Example/PrebidDemoKotlin/src/androidTest/java/org/prebid/mobile/prebidkotlindemo/ui/NativeAdsTest.kt
- Example/PrebidDemoKotlin/src/main/AndroidManifest.xml
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/activities/ads/gam/original/GamOriginalApiInStreamActivity.kt
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/activities/ads/gam/original/GamOriginalApiNativeInAppActivity.kt
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/activities/ads/gam/original/GamOriginalApiNativeInBannerActivity.kt
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/testcases/TestCaseRepository.kt
- Example/PrebidDemoKotlin/src/main/res/values/strings.xml
> Add in-stream and native in app examples

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/Regs.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/parameters/UserConsentParameterBuilder.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/sdk/deviceData/managers/UserConsentManager.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/networking/parameters/UserConsentParameterBuilderTest.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/sdk/deviceData/managers/UserConsentManagerTest.java
Put GPP string into the bid request. 
Closes #532.
> Support GPP string 

- Example/PrebidDemoJava/build.gradle
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/javademo/CustomApplication.java
- Example/PrebidDemoKotlin/build.gradle
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/activities/ads/admob/AdMobDisplayBanner320x50Activity.kt
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/activities/ads/gam/original/GamOriginalApiNativeInAppActivity.kt
- Example/PrebidInternalTestApp/build.gradle
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/HeaderBiddingViewModelFactory.kt
- PrebidMobile/android.gradle
- PrebidMobile/publisher.gradle
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- tools/drprebid/build.gradle
Clean build.gradle files. Fix warning during apps assembling. Rename global variables in root build.gradle. Update Kotlin version. Closes #529.
> Update Gradle to 7.4

- Example/PrebidDemoJava/build.gradle
- Example/PrebidDemoKotlin/build.gradle
- Example/PrebidInternalTestApp/build.gradle
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/gam/rendering/GamOutstreamFragment.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/ppm/PpmVideoFragment.kt
- Example/PrebidInternalTestApp/src/main/res/layout/fragment_bidding_banner_video.xml
- PrebidMobile/publisher.gradle
- README.md
- build.gradle
- gradle.properties
- scripts/Maven/PrebidMobile-admobAdapters-pom.xml
- scripts/Maven/PrebidMobile-core-pom.xml
- scripts/Maven/PrebidMobile-gamEventHandlers-pom.xml
- scripts/Maven/PrebidMobile-maxAdapters-pom.xml
- scripts/Maven/PrebidMobile-pom.xml
> Preparation for release 2.0.7

- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/javademo/activities/ads/gam/original/GamOriginalApiDisplayBanner300x250.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/javademo/activities/ads/gam/original/GamOriginalApiDisplayBanner320x50.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/javademo/activities/ads/gam/original/GamOriginalApiVideoBanner.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/javademo/activities/ads/gam/original/GamOriginalApiVideoInStream.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/javademo/activities/ads/gam/original/GamOriginalApiVideoInterstitial.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/javademo/activities/ads/gam/original/GamOriginalApiVideoRewarded.java
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/activities/ads/gam/original/GamOriginalApiDisplayBanner300x250Activity.kt
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/activities/ads/gam/original/GamOriginalApiDisplayBanner320x50Activity.kt
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/activities/ads/gam/original/GamOriginalApiDisplayBannerMultiSizeActivity.kt
Refactor some examples with parameters.
> [Demo Apps] Add setters for additional parameters where skipped

- .github/workflows/issue_prioritization.yml
Also see https://github.com/prebid/Prebid.js/pull/9466
> Update issue tracker for GH API changes

- Example/PrebidDemoKotlin/src/androidTest/java/org/prebid/mobile/prebidkotlindemo/ui/VideoAdsTest.kt
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/data/bid/BidResponse.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/bidding/data/bid/BidResponseTest.java
- PrebidMobile/PrebidMobile-core/src/test/resources/BidResponseTest/keywords_all_with_cache_id.json
- PrebidMobile/PrebidMobile-core/src/test/resources/BidResponseTest/keywords_empty.json
- PrebidMobile/PrebidMobile-core/src/test/resources/BidResponseTest/keywords_not_all.json
> Remove hb_size from required keywords 

- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/MainActivity.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/utils/GppHelper.kt
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/Regs.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/networking/parameters/UserConsentParameterBuilderTest.java
> Convert GPP sid to int array 

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidNativeAd.java
> Add null pointer checker in the PrebidNativeAd

- Example/PrebidDemoJava/src/main/AndroidManifest.xml
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/javademo/activities/ads/gam/original/GamOriginalApiNativeStyles.java
- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/javademo/testcases/TestCaseRepository.java
- Example/PrebidDemoJava/src/main/res/values/strings.xml
- Example/PrebidDemoKotlin/src/androidTest/java/org/prebid/mobile/prebidkotlindemo/ui/NativeAdsTest.kt
- Example/PrebidDemoKotlin/src/main/AndroidManifest.xml
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/activities/ads/gam/original/GamOriginalApiNativeStylesActivity.kt
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/testcases/TestCaseRepository.kt
- Example/PrebidDemoKotlin/src/main/res/values/strings.xml
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/utils/DemoItemProvider.kt
- Example/PrebidInternalTestApp/src/main/res/values/strings.xml
> Update native styles examples in the apps

- Example/PrebidDemoJava/src/main/AndroidManifest.xml
- Example/PrebidDemoJava/src/main/res/xml/network_security_config.xml
- Example/PrebidDemoKotlin/src/main/AndroidManifest.xml
The app contains network config, but it's not full and it's not applied to the app.
> Apply network config for Java app

- Example/PrebidDemoJava/src/main/java/org/prebid/mobile/javademo/CustomApplication.java
- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/CustomApplication.kt
- PrebidMobile/PrebidMobile-admobAdapters/src/main/java/org/prebid/mobile/admob/PrebidBaseAdapter.java
- PrebidMobile/PrebidMobile-core/build.gradle
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/data/InitializationStatus.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/exceptions/InitError.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/listeners/SdkInitializationListener.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/BaseNetworkTask.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/tracking/ServerConnection.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/sdk/SdkInitializer.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/sdk/StatusRequester.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/ExternalUIDTest.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/PrebidMobileTest.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/TargetingParamsTest.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/reflection/Reflection.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/reflection/sdk/PrebidMobileReflection.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilderTest.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/sdk/PrebidMobileTest.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/sdk/SdkInitializerTest.java
- PrebidMobile/PrebidMobile-maxAdapters/src/main/java/com/applovin/mediation/adapters/PrebidMaxMediationAdapter.java
- scripts/Maven/PrebidMobile-core-pom.xml
> Changes for /status endpoint

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilder.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilderTest.java
> Omid signals 

- Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/activities/MainActivity.kt
- README.md
> Fix demo crash

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/data/bid/BidResponse.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/bidding/data/bid/BidResponseTest.java
- PrebidMobile/PrebidMobile-maxAdapters/src/main/java/com/applovin/mediation/adapters/prebid/managers/MaxBannerManager.java
Closes #562. 
Also add null pointer check for Applovin MAX to clean exceptional logs.
> Change the bid response parsing in order not to treat No Bids as an error

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/modelcontrollers/Requester.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/utils/helpers/AdIdManager.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/networking/modelcontrollers/BidRequesterTest.java
> Fix weak reference problem in Requester

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/session/manager/OmAdSessionManager.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/utils/helpers/AppInfoManager.java
- PrebidMobile/PrebidMobile-maxAdapters/src/main/java/com/applovin/mediation/adapters/PrebidMaxMediationAdapter.java
- PrebidMobile/PrebidMobile-maxAdapters/src/main/java/com/applovin/mediation/adapters/prebid/managers/MaxBannerManager.java
- PrebidMobile/PrebidMobile-maxAdapters/src/main/java/com/applovin/mediation/adapters/prebid/managers/MaxInterstitialManager.java
- PrebidMobile/PrebidMobile-maxAdapters/src/main/java/com/applovin/mediation/adapters/prebid/managers/MaxNativeManager.java
Fix Applovin MAX adapter initialization. Add null pointer checkers. Fix not catchable exception in Prebid SDK when called from a background thread.
> Applovin MAX fixes

- Example/PrebidDemoKotlin/src/androidTest/java/org/prebid/mobile/prebidkotlindemo/ui/BaseAdsTest.kt
- Example/PrebidDemoKotlin/src/androidTest/java/org/prebid/mobile/prebidkotlindemo/ui/MraidAdsTest.kt
- Example/PrebidDemoKotlin/src/androidTest/java/org/prebid/mobile/prebidkotlindemo/ui/VideoAdsTest.kt
Stop activities from previous tests. Replace unstable and infinite view search rules.
> Smoke tests improvements

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/rendering/PrebidDisplayView.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/rendering/pluginrenderer/PrebidMobilePluginRenderer.java
Closes #614.  Closes #613. Closes #578.
> Fix session finish problem

- README.md
- build.gradle
- scripts/Maven/PrebidMobile-admobAdapters-pom.xml
- scripts/Maven/PrebidMobile-core-pom.xml
- scripts/Maven/PrebidMobile-gamEventHandlers-pom.xml
- scripts/Maven/PrebidMobile-maxAdapters-pom.xml
- scripts/Maven/PrebidMobile-pom.xml
> Release 2.1.0

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/CacheManager.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/mraid/handler/FetchPropertiesHandler.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/utils/helpers/AdIdManager.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/views/browser/BrowserControls.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/views/interstitial/InterstitialVideo.java
> Replace deprecated Handler constructor

- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/AdFragment.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/HeaderBiddingFragment.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/testing/MemoryLeakTestingOriginalApiBannerFragment.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/testing/MemoryLeakTestingRenderingApiBannerFragment.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/testing/MemoryLeakTestingRenderingApiInterstitialFragment.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/utils/BaseFragment.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/utils/DemoItemProvider.kt
- Example/PrebidInternalTestApp/src/main/res/navigation/bidding_navigation.xml
- Example/PrebidInternalTestApp/src/main/res/values/strings.xml
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/AdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/rendering/BannerView.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/rendering/InterstitialAdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/display/InterstitialController.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/interfaces/StandaloneInterstitialEventHandler.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/BaseNetworkTask.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/modelcontrollers/Requester.java
> Memory leak problem

- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/ppm/PpmBannerSpecialSymbolsFragment.kt
- Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/utils/DemoItemProvider.kt
- Example/PrebidInternalTestApp/src/main/res/navigation/bidding_navigation.xml
- Example/PrebidInternalTestApp/src/main/res/values/strings.xml
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/BaseNetworkTask.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/networking/BaseNetworkTaskTest.java
> Support all ISO characters 

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/AdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/mediation/MediationBaseAdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/rendering/BannerView.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/rendering/BaseInterstitialAdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/loader/BidLoader.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/modelcontrollers/BidRequester.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/modelcontrollers/Requester.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/sdk/PrebidContextHolder.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/bidding/loader/BidLoaderTest.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/networking/modelcontrollers/BidRequesterTest.java
In BidLoader use Context provided during SDK initialization. Fix tests.
Closes #633.
> Add check if SDK was initialized inside BidLoader

- README.md
- build.gradle
- scripts/Maven/PrebidMobile-admobAdapters-pom.xml
- scripts/Maven/PrebidMobile-core-pom.xml
- scripts/Maven/PrebidMobile-gamEventHandlers-pom.xml
- scripts/Maven/PrebidMobile-maxAdapters-pom.xml
- scripts/Maven/PrebidMobile-pom.xml
> Release 2.1.1

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java
- PrebidMobile/PrebidMobile-gamEventHandlers/src/test/java/org/prebid/mobile/eventhandlers/global/GoogleAdVersionTest.java
- scripts/Maven/PrebidMobile-admobAdapters-pom.xml
- scripts/Maven/PrebidMobile-gamEventHandlers-pom.xml
> Update GMA SDK

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/mediation/MediationInterstitialAdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/rendering/InterstitialAdUnit.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/api/mediation/MediationInterstitialAdUnitTest.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/api/rendering/InterstitialAdUnitTest.java
> Set 2 default ad formats for interstitial

- README.md
- build.gradle
- scripts/Maven/PrebidMobile-admobAdapters-pom.xml
- scripts/Maven/PrebidMobile-core-pom.xml
- scripts/Maven/PrebidMobile-gamEventHandlers-pom.xml
- scripts/Maven/PrebidMobile-maxAdapters-pom.xml
- scripts/Maven/PrebidMobile-pom.xml
> Release 2.1.3

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilder.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilderTest.java
Added `pbadslot` field. 
[Issue](https://github.com/prebid/prebid-mobile-android/issues/810).
> Send `pbadslot` field together with `adslot`

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/TargetingParams.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/parameters/UserParameters.java
https://github.com/prebid/prebid-mobile-ios/issues/1005
> Deprecated YOB/Age/Gender

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/TargetingParams.java
https://github.com/prebid/prebid-mobile-ios/issues/1003
> Deprecated setUserCustomData

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java
- PrebidMobile/PrebidMobile-gamEventHandlers/src/test/java/org/prebid/mobile/eventhandlers/global/GoogleAdVersionTest.java
- gradle/libs.versions.toml
- scripts/Maven/PrebidMobile-admobAdapters-pom.xml
- scripts/Maven/PrebidMobile-gamEventHandlers-pom.xml
Return the GAM auto-update feature.
> Update GAM to the latest version

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/SharedId.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/SharedIdTest.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/sdk/JSLibraryManagerTest.java
Fix unit tests for the new release.
> Fix shared id tests

- Example/PrebidDemoJava/build.gradle
- Example/PrebidDemoKotlin/build.gradle
- Example/PrebidInternalTestApp/build.gradle
- PrebidMobile/PrebidMobile-admobAdapters/build.gradle
- PrebidMobile/PrebidMobile-admobAdapters/src/main/java/org/prebid/mobile/admob/PrebidRewardedAdapter.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java
- PrebidMobile/PrebidMobile-gamEventHandlers/build.gradle
- PrebidMobile/PrebidMobile-gamEventHandlers/src/test/java/org/prebid/mobile/UtilTest.java
- PrebidMobile/PrebidMobile-gamEventHandlers/src/test/java/org/prebid/mobile/eventhandlers/GamBannerEventHandlerTest.java
- PrebidMobile/PrebidMobile-gamEventHandlers/src/test/java/org/prebid/mobile/eventhandlers/GamInterstitialEventHandlerTest.java
- PrebidMobile/PrebidMobile-gamEventHandlers/src/test/java/org/prebid/mobile/eventhandlers/GamRewardedEventHandlerTest.java
- PrebidMobile/PrebidMobile-gamEventHandlers/src/test/java/org/prebid/mobile/eventhandlers/PublisherAdViewWrapperTest.java
- PrebidMobile/PrebidMobile-gamEventHandlers/src/test/java/org/prebid/mobile/eventhandlers/PublisherInterstitialAdWrapperTest.java
- PrebidMobile/PrebidMobile-gamEventHandlers/src/test/java/org/prebid/mobile/eventhandlers/RewardedAdWrapperTest.java
- PrebidMobile/PrebidMobile-gamEventHandlers/src/test/java/org/prebid/mobile/eventhandlers/utils/GamUtilsTest.java
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- scripts/Maven/PrebidMobile-admobAdapters-pom.xml
- scripts/Maven/PrebidMobile-gamEventHandlers-pom.xml
> Update GAM to 24

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/AdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/Host.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/TargetingParams.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/mediation/MediationBaseAdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/mediation/MediationNativeAdUnit.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/rendering/BannerView.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/rendering/BaseInterstitialAdUnit.java
Issues: 
[#1009](https://github.com/prebid/prebid-mobile-ios/issues/1009)
[#1007](https://github.com/prebid/prebid-mobile-ios/issues/1007)
[#1006](https://github.com/prebid/prebid-mobile-ios/issues/1006)
> Deprecate methods and properties for 3.0

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/Signals.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/VideoParameters.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/imps/Video.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilder.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/AdUnitSuccessorTest.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/imps/VideoTest.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilderTest.java
#776
- Extends video parameters with 'battr' property.
> Blocked creative attribute

- PrebidMobile/PrebidMobile-maxAdapters/src/main/java/com/applovin/mediation/adapters/PrebidMaxMediationAdapter.java
> Fix Applovin adapter 

- scripts/js/om_impression_tracker.js
[Original issue](https://github.com/prebid/prebid-mobile-ios/issues/1095).
> Add OM impression tracker JS script

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/utils/helpers/Utils.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/utils/helpers/UtilsTest.java
- PrebidMobile/PrebidMobile-core/src/test/resources/ad_inline_contains_single_quotes.xml
issue https://github.com/prebid/prebid-mobile-android/issues/853
> fix vast regex to accept single quotes

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/imps/Video.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilder.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilderTest.java
- scripts/Maven/PrebidMobile-admobAdapters-pom.xml
- scripts/Maven/PrebidMobile-gamEventHandlers-pom.xml
> isSkippable incorrect type

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java
- scripts/Maven/PrebidMobile-admobAdapters-pom.xml
- scripts/Maven/PrebidMobile-gamEventHandlers-pom.xml
> Bump GAM to 24.4.0

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/video/AdViewProgressUpdateTask.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/video/ExoPlayerView.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/views/AdViewManager.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/video/AdViewProgressUpdateTaskTest.java
> Fix double start

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/original/MultiformatAdUnitFacade.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/original/PrebidRequest.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/configuration/AdUnitConfiguration.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/models/AdPosition.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/api/original/MultiformatAdUnitFacadeTest.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilderTest.java
Add separate ad position setter for BannerParameters and VideoParameters in multiformat ad unit. 
Closes #883.
> Ad position for multiformat ad unit

- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/data/bid/Bid.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/data/bid/BidResponse.java
- PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/data/bid/Prebid.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/bidding/data/bid/BidResponseTest.java
- PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/models/CreativeModelMakerBidsTest.java
- PrebidMobile/PrebidMobile-core/src/test/resources/BidResponseTest/bid_type_banner.json
- PrebidMobile/PrebidMobile-core/src/test/resources/BidResponseTest/bid_type_none_with_html_content.json
- PrebidMobile/PrebidMobile-core/src/test/resources/BidResponseTest/bid_type_none_with_vast_content.json
- PrebidMobile/PrebidMobile-core/src/test/resources/BidResponseTest/bid_type_video.json
- PrebidMobile/PrebidMobile-core/src/test/resources/auction_response_video_type.json
> Is video check as on iOS
