buildprebid.sh

Fix for Issue 3 & 6
- Build process does not stop when one of steps is failing
- Build process leaves a gradle process running in the background

Github feedback on build script fix

---

PrebidMobile/PrebidServerAdapter/src/main/java/org/prebid/mobile/prebidserver/ServerConnector.java
PrebidMobile/PrebidServerAdapter/src/main/java/org/prebid/mobile/prebidserver/internal/Settings.java
PrebidMobile/PrebidServerAdapter/src/test/java/org/prebid/mobile/prebidserver/PrebidServerAdapterTest.java

Issue is from https://github.com/prebid/prebid-mobile-android/issues/9
This fix gives developer the ability to override the time out by changing Settings.REQUEST_TIME_OUR_MILLIS

Grant ability to override request time out for http connection

---

.gitignore
.travis.yml
PrebidMobile/DemoApp/build.gradle
PrebidMobile/DemoApp/src/main/java/org/prebid/mobile/demoapp/DemoActivity.java
PrebidMobile/DemoApp/src/main/java/org/prebid/mobile/demoapp/dfpdemofragments/DFPBannerFragment.java
PrebidMobile/DemoApp/src/main/java/org/prebid/mobile/demoapp/dfpdemofragments/DFPInterstitialFragment.java
PrebidMobile/IntegrationTests/Gemfile
PrebidMobile/IntegrationTests/Gemfile.lock
PrebidMobile/IntegrationTests/features/base_test.feature
PrebidMobile/IntegrationTests/features/step_definitions/calabash_steps.rb
PrebidMobile/IntegrationTests/run_tests_local.sh
testprebid.sh

Updated Xamarin tests for new demo app and added backdoor to correctly pull DFP Banner webview class. This PR should trigger the Xamarin tests on the cloud.
TODO: the Interstitial tests for DFP & MoPub aren't really working properly yet

Update Xamarin tests and run them through Travis CI

---

PrebidMobile/IntegrationTests/features/step_definitions/calabash_steps.rb
testprebid.sh

The old device of the tests were not rendering the ad properly, updating to two new devices and modified the tests to be more robust.

Move to new devices for integration tests

---

.travis.yml
PrebidMobile/DemoApp/src/main/java/org/prebid/mobile/demoapp/MainActivity.java
PrebidMobile/DemoApp/src/main/java/org/prebid/mobile/demoapp/PrebidApplication.java
PrebidMobile/PrebidMobileCore/src/main/java/org/prebid/mobile/core/BidManager.java
PrebidMobile/PrebidMobileCore/src/main/java/org/prebid/mobile/core/CacheManager.java
PrebidMobile/PrebidMobileCore/src/main/java/org/prebid/mobile/core/InterstitialAdUnit.java
PrebidMobile/PrebidMobileCore/src/main/java/org/prebid/mobile/core/Prebid.java
PrebidMobile/PrebidMobileCore/src/main/java/org/prebid/mobile/core/TargetingParams.java
PrebidMobile/PrebidMobileCore/src/test/java/org/prebid/mobile/core/BidManagerTest.java
PrebidMobile/PrebidMobileCore/src/test/java/org/prebid/mobile/core/PrebidInitTest.java
PrebidMobile/PrebidMobileCore/src/test/java/org/prebid/mobile/core/TargetingParamsTest.java
PrebidMobile/PrebidServerAdapter/README.md
PrebidMobile/PrebidServerAdapter/src/main/java/org/prebid/mobile/prebidserver/PrebidServerAdapter.java
PrebidMobile/PrebidServerAdapter/src/main/java/org/prebid/mobile/prebidserver/internal/Settings.java
PrebidMobile/PrebidServerAdapter/src/test/java/org/prebid/mobile/prebidserver/PrebidServerAdapterTest.java
PrebidMobile/UnitTestUtils/build.gradle
PrebidMobile/build.gradle
PrebidMobile/gradle/wrapper/gradle-wrapper.properties
testprebid.sh

This PR includes changes that works with latest Prebid Server openrtb endpoint.
Note that this is tested only with local test server, haven't tested with https request (SSL creatives), and cache function for MoPub builds.
Actual endpoint switch will happen later when Prebid Server fully rolls out its open rtb endpoint. If we use endpoint from AppNexus in the prebid server adapter, we still anticipate the OPEN RTB protocol stays the same.

Openrtb compliant Prebid Server Adapter

---

PrebidMobile/PrebidMobileCore/src/main/java/org/prebid/mobile/core/CacheManager.java

- No more anonymous runnables with implicit outer references to CacheManager and its Context referencing WebView property
- Reuse Handler instance for setupBidCleanUpRunnable (and its inner Runnable), setupWebCache
- Reuse WebSettings reference when initializing the dfpWebCache settings, Dalvik isn't too good at code optimization
- Removed unnecessary 'long now' instance, only used once when cleaning up the cache
- Suggestion as a next refactor: get rid of one liner methods setupWebCache, setupBidCleanUpRunnable, just invoke the handler.post calls on the constructor

CacheManager no longer leaks Contexts and refactors

---

Maven/pom.xml
PrebidMobile/PrebidMobileCore/build.gradle

This will help with the integration in other projects, when pulling more code can be a potential problem due to the DEX limitations in android.

reduce dependency only to commons-lang3 and use implementation instead of deprecated compile in gradle

---

Maven/pom.xml
PrebidMobile/PrebidMobileCore/build.gradle
PrebidMobile/PrebidMobileCore/src/main/java/org/prebid/mobile/core/CacheManager.java
PrebidMobile/PrebidMobileCore/src/main/java/org/prebid/mobile/core/StringUtils.java
PrebidMobile/PrebidMobileCore/src/test/java/org/prebid/mobile/core/StringUtilsTest.java

The context of this change is try to avoid the `commons-lang3` dependency. Only one left is the `StringEscapeUtils.escapeEcmaScript` call.

removed commons-lang3 dependency

---

PrebidMobile/PrebidServerAdapter/src/main/java/org/prebid/mobile/prebidserver/internal/Settings.java

We are getting this crash report
```
android.util.AndroidRuntimeException: 
at android.webkit.WebViewFactory.getFactoryClass (WebViewFactory.java:174)
at android.webkit.WebViewFactory.getProvider (WebViewFactory.java:109)
at android.webkit.WebView.getFactory (WebView.java:2194)
at android.webkit.WebView.ensureProviderCreated (WebView.java:2189)
at android.webkit.WebView.setOverScrollMode (WebView.java:2248)
at android.view.View.<init> (View.java:3701)
at android.view.View.<init> (View.java:3797)
at android.view.ViewGroup.<init> (ViewGroup.java:503)
at android.widget.AbsoluteLayout.<init> (AbsoluteLayout.java:55)
at android.webkit.WebView.<init> (WebView.java:544)
at android.webkit.WebView.<init> (WebView.java:489)
at android.webkit.WebView.<init> (WebView.java:472)
at …
```

catch AndroidRuntimeException when getting the device WebView userAgent

---

PrebidMobile/API1.0/src/main/java/org/prebid/mobile/Host.java
PrebidMobile/API1.0/src/main/java/org/prebid/mobile/PrebidMobile.java

Default host was changed from Host.APPNEXUS to Host.CUSTOM.
If a publisher does not call setPrebidServerHost() Log error will be printed
The Doc hint looks like

Change host reference

---

.travis.yml
PrebidMobile/API1.0/src/main/java/org/prebid/mobile/Util.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/UtilTest.java
PrebidMobile/API1.0Demo/src/androidTest/java/org/prebid/mobile/app/DFPBannerComplexTest.java
PrebidMobile/API1.0Demo/src/main/java/org/prebid/mobile/app/DemoActivity.java

[GitHub issue](https://github.com/prebid/prebid-mobile-ios/issues/175)
1. Multisize support was added
2. UnitTests were added
3. UI test was added

[Android][AdManager][Banner] An ad is not rendered properly. Part 2

---

PrebidMobile/API1.0/src/main/java/org/prebid/mobile/PrebidMobile.java
PrebidMobile/API1.0/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/DemandFetcherTest.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/PrebidMobileTest.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/ResultCodeTest.java

public should be the field timeoutMillis so it could be changed if needed from the publisher code when integrating the SDK:
"PrebidMobile.timeoutMillis = 1000;"
I removed public for the var "TIMEOUT_MILLIS" which is final so public is useless.
Issue   #111

Fix prebid timeout editable

---

PrebidMobile/API1.0/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
PrebidMobile/API1.0/src/main/java/org/prebid/mobile/TargetingParams.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/TargetingParamsTest.java

GitHub issue #110
1. COPPA support was added
The `PreferenceManager`is being used for saving flag
API:
```
TargetingParams.setSubjectToCOPPA(true);
```
OpenRTB:
```
"request.regs.coppa": 1
```
2. Unit test tests were added

Support for COPPA

---

PrebidMobile/API1.0/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/testutils/MockPrebidServerResponses.java
PrebidMobile/API1.0/src/test/resources/PrebidServerHtmlUnreachableFromRubiconInvalidResponse.html
PrebidMobile/API1.0/src/test/resources/PrebidServerInvalidAccountIdFromRubicon.json
PrebidMobile/API1.0/src/test/resources/PrebidServerInvalidConfigIdFromRubicon.json

GitHub issue #122 
1. PREBID_SERVER_ERROR was made as default error
2. Unit tests were modified

API. No auction response

---

PrebidMobile/API1.0/src/main/java/org/prebid/mobile/Util.java
PrebidMobile/API1.0/src/main/java/org/prebid/mobile/addendum/AdViewUtils.java
PrebidMobile/API1.0/src/main/java/org/prebid/mobile/addendum/Pair.java
PrebidMobile/API1.0/src/main/java/org/prebid/mobile/addendum/PbError.java
PrebidMobile/API1.0/src/main/java/org/prebid/mobile/addendum/PbFindSizeError.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/UtilTest.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/addendum/AdViewUtilsTest.java
PrebidMobile/API1.0Demo/src/main/java/org/prebid/mobile/app/DemoActivity.java

GitHub issue #124 
What were changed:
1. Fixed bug when a callback is not being called on a client side
2. A new method `AdViewUtils.findPrebidCreativeSize()` was created to support success and failure handlers 
3. The old resize function(`findPrebidCreativeSize(View, CreativeSizeCompletionHandler)`) was marked as deprecated and it's still possible to use it (to support compatibility)
The latest API for resize function looks like
```
dfpAdView.setAdListener(new AdListener() {
@Override
public void onAdLoaded() {
super.onAdLoaded();
AdViewUtils.findPrebidCreativeSize(dfpAdView, new AdViewUtils.PbFindSizeListener() {
@Override
public void success(int width, int height) {
dfpAdView.setAdSizes(new AdSize(width, height));
}
@Override
public void failure(@NonNull PbFindSizeError error) { …
```

Update resize function

---

PrebidMobile/API1.0/src/main/java/org/prebid/mobile/AdUnit.java
PrebidMobile/API1.0/src/main/java/org/prebid/mobile/InterstitialAdUnit.java
PrebidMobile/API1.0/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
PrebidMobile/API1.0/src/main/java/org/prebid/mobile/RequestParams.java
PrebidMobile/API1.0/src/main/java/org/prebid/mobile/Util.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/InterstItialAdUnitTest.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/RequestParamsTest.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/UtilTest.java

[GitHub issue](https://github.com/prebid/prebid-mobile-android/issues/126)
1. A new constructor `InterstitialAdUnit(String, int, int)` was added
2. Unit tests were added
The new API looks like:
```
new InterstitialAdUnit("1001-1", 50, 70);
```
OpenRTB request:
```
request.device.ext.prebid.interstitial: {"minwidthperc": 50, "minheightperc": 70}
```
TODO:
1. Update the doc

Advanced interstitial support

---

PrebidMobile/API1.0/src/main/java/org/prebid/mobile/AdUnit.java
PrebidMobile/API1.0/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
PrebidMobile/API1.0/src/main/java/org/prebid/mobile/RequestParams.java
PrebidMobile/API1.0/src/main/java/org/prebid/mobile/TargetingParams.java
PrebidMobile/API1.0/src/main/java/org/prebid/mobile/Util.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/AdUnitTest.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/BannerAdUnitTest.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/DemandFetcherTest.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/InterstItialAdUnitTest.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/RequestParamsTest.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/ResultCodeTest.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/TargetingParamsTest.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/UtilTest.java
PrebidMobile/API1.0/src/test/java/org/prebid/mobile/testutils/Utils.java

GitHub issue #131 
//ACL block
1. `Access Control List` 
`TargetingParams` API:
``` Java
void addBidderToAccessControlList(String bidderName)
void removeBidderFromAccessControlList(String bidderName)
void clearAccessControlList()
```
Example:
``` Java
TargetingParams.addBidderToAccessControlList(TargetingParams.BIDDER_NAME_RUBICON_PROJECT);
```
OpenRTB request:
``` JSON
"ext": {
"prebid": {
"data": {
"bidders": [
"rubicon"]
}
}
}
```
//data block
2. `global user data`
`TargetingParams` API:
``` Java
void addUserData(String key, String value)
void updateUserData(String key, Set<String> value)
void removeUserData(String key)
void clearUserData()
```
Example:
``` Java
TargetingParams.addUserData("globalUserDataKey1", "globalUserDataValue1")
```
OpenRTB request:
``` JSON
"user": {
"ext": { …
```

Support for First Party Data

---

PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/DemandFetcher.java

https://github.com/prebid/prebid-mobile-android/issues/156
FetcherThreads and DemandThreads persist and new threads seem to be created for each fetch. If the app is used long enough, there are too many threads, causing a crash.
With this fix or one like it, I believe existing applications using this library won't have to make any updates in their own code unless they use autoRefresh, in which case they need to make sure to stopAutoRefresh on the adUnits when destroying an ad (which would already been good practice).

Fix issue #156: FetcherThreads and DemandThreads persist after task completion

---

Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/DemoActivity.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/AdUnit.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/RequestParams.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/Signals.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/VideoAdUnit.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/VideoBaseAdUnit.java
PrebidMobile/src/test/java/org/prebid/mobile/AdUnitSuccessorTest.java
PrebidMobile/src/test/java/org/prebid/mobile/DemandFetcherTest.java
PrebidMobile/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
PrebidMobile/src/test/java/org/prebid/mobile/RequestParamsTest.java

**Changes**
`Signals.Placement` class was added to replace `PlacementType`
**API**
There are two ways to create a `Signal` object:
1. Use predefined constants
2. Manually construct a new instance
``` Java
//Interstitial
Signals.Placement interstitial = Signals.Placement.Interstitial;
Signals.Placement interstitial = new Signals.Placement(5);
```
Example
``` Java
VideoBaseAdUnit.Parameters parameters = new VideoBaseAdUnit.Parameters();
parameters.setPlacement(Signals.Placement.Interstitial);
VideoInterstitialAdUnit adUnit = new VideoInterstitialAdUnit("1001-1");
adUnit.setParameters(parameters);
```
**Notes:**
If publisher does not set `placement` for `VideoInterstitialAdUnit` or `RewardedVideoAdUnit`, value `5` is used by default
**Deprecated**
``` Java
//Enums
VideoAdUnit.PlacementType …
```

Video signals improvement

---

Example/PrebidDemoJava/src/androidTest/java/org/prebid/mobile/app/AdManagerComplexTest.java
Example/PrebidDemoJava/src/androidTest/java/org/prebid/mobile/app/DFPBannerComplexTest.java
Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/DemoActivity.java
Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/DemoActivity.kt
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/Util.java
PrebidMobile/src/test/java/org/prebid/mobile/UtilTest.java

Description and the main idea #198
As a developer I want to have a possibility to add extra `custom targeting` **after** bids were retrieved
Now publisher can pass an `PublisherAdRequest.Builder`
``` Java
final PublisherAdRequest.Builder builder = new PublisherAdRequest.Builder();
adUnit.fetchDemand(builder, new OnCompleteListener() {
@Override
public void onComplete(ResultCode resultCode) {
builder.addCustomTargeting("key1", "value1");
PublisherAdRequest request = builder.build();
amBanner.loadAd(request);
}
});
```

Modify custom targeting after the auction happened

---

Example/PrebidDemoJava/src/androidTest/java/org/prebid/mobile/app/AdManagerComplexTest.java
Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/DemoActivity.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/AdUnit.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/OnCompleteListener2.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/Util.java

[GitHub issue for iOS](https://github.com/prebid/prebid-mobile-ios/issues/303)
A new overloaded `fetchDemand` method was created
``` Java
void fetchDemand(@NonNull final OnCompleteListener2 listener)
```
This function:
1. does not accept an `AdServerObject`(AdManager or MoPub) as a result it does not modify it under the hood
2. returns Key/Value `targeting` pairs from `auction` response
Publisher is responsible for passing returned result into `AdServerObject`
A good example is `RewardedVideo` for `MoPub` AdServer. 
Usage example:
``` Java
func loadMPRewardedVideo() {
private void loadMPRewardedVideo() {
adUnit.fetchDemand(new OnCompleteListener2() {
@Override
public void onComplete(ResultCode resultCode, Map<String, String> unmodifiableMap) {
//copy  of unmodifiableMap. It is an extra …
```

Bids Response hook

---

PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/http/HTTPPost.java
PrebidMobile/src/test/java/org/prebid/mobile/PrebidNativeNativeTest.java

This PR shows an alternative way to fix the concurrency issue mentioned in next issues: https://github.com/prebid/prebid-mobile-android/issues/243, https://github.com/prebid/prebid-mobile-android/issues/244, https://github.com/prebid/prebid-mobile-android/issues/246, https://github.com/prebid/prebid-mobile-android/issues/247, https://github.com/prebid/prebid-mobile-android/issues/248, https://github.com/prebid/prebid-mobile-android/issues/249
Original PR which also has the concurrency fixes: https://github.com/prebid/prebid-mobile-android/pull/245
The reason for this alternative PR is that `HttpPost.onPostExecute` (and all future processing in `PrebidServerAdapter`) was initially executed on the main thread. Some of the methods in `PrebidServerAdapter` are marked with `@MainThread` …

PrebidServerAdapter errors alternative solution

---

PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java

Issue description can be found here: https://github.com/prebid/prebid-mobile-android/issues/263
**Commit details:**
fix(PrebidServerAdapter):
- Executing timeout listener notification on MainThread

Fix ConcurrentModificationException in apply(Util.java:417) 

---

Example/PrebidInternalTestApp/src/androidTest/java/org/prebid/mobile/renderingtestapp/uiAutomator/tests/gam/GamNativeTests.java
Example/PrebidInternalTestApp/src/androidTest/java/org/prebid/mobile/renderingtestapp/uiAutomator/tests/ppm/PpmNativeTests.java
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/gam/GamNativeFeedFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/gam/GamNativeFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/ppm/PpmNativeFeedFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/ppm/PpmNativeFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/ppm/PpmNativeLinksFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/ppm/PpmNativeVideoFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/utils/DemoItemProvider.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/utils/adapters/NativeFeedAdapter.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/utils/adapters/NativeGamFeedAdapter.kt
Example/PrebidInternalTestApp/src/main/res/navigation/bidding_navigation.xml
PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/bidding/display/NativeAdUnit.java
PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/models/AdConfiguration.java

NativeAdUnit from rendering is unavailable for publishers now. Disabled native test cases in InternalTestsApp. Checked and recompiled all modules and apps in the project. #280

Make private native ad from rendering. 

---

PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/AdUnit.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/ContentObject.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/RequestParams.java
PrebidMobile/src/test/java/org/prebid/mobile/AdUnitContentTest.java
PrebidMobile/src/test/java/org/prebid/mobile/PrebidNativeNativeTest.java
PrebidMobile/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
PrebidMobile/src/test/java/org/prebid/mobile/RequestParamsTest.java
build.gradle

This PR aims to provide more precise targeting information with bid request. When PBS asks for bids for an ad slot, bidders have very little information about the user. This is caused by latest developments where users choose to opt-out of sharing their AAID and such.
We can at least supply bidders with some context, like what content the user is looking at when they see an ad. Google ad manager calls this technique content mapping: https://support.google.com/admanager/answer/11050896?hl=en
Publishers roughly map views in their apps to pages on their websites. Then the targeting information already collected for pages on publisher’s website can be used to better target ad slots that appear in the apps. For this to work bidders needs to receive information which page would this ad slot …

Pass app:content:url property into bid request

---

PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/AdUnit.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/DemandFetcher.java
PrebidMobile/build.gradle
PrebidMobile/src/test/java/org/prebid/mobile/AdUnitSuccessorTest.java
PrebidMobile/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
build.gradle

This PR introduces changes described in the following issue: 
https://github.com/prebid/prebid-mobile-ios/issues/393
chore(build.gradle):
- Updated compile version to 30
- Updated robolectric version to 4.3.1
feat(AdUnit):
- Added ability to resume autorefresh
- Added unit tests

Introduce consistent refresh policy

---

PrebidMobile/PrebidMobile-rendering/.gitignore
scripts/Maven/deployOpenMeasurement.sh
scripts/Maven/deployPrebidMobile.sh

Created deployOpenMeasurement.sh file. #318

Separate deploy file for Open Measurement SDK

---

Example/PrebidDemoJava/build.gradle
Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/RubiconInstreamVideoIMADemoActivity.java
Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/XandrInstreamVideoGamActivity.java

Commented unavailable classes after jCenter dependencies update.

Fix updated dependencies 

---

Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/AdTypesRepository.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/admob/AdMobInterstitialFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/admob/AdMobInterstitialRandomFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/admob/AdMobRewardedFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/admob/AdMobRewardedRandomFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/admob/FlexibleAdMobBannerFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/utilities/version/VersionInfoFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/utils/DemoItemProvider.kt
Example/PrebidInternalTestApp/src/main/res/layout/events_admob_rewarded.xml
Example/PrebidInternalTestApp/src/main/res/layout/fragments_version_info.xml
Example/PrebidInternalTestApp/src/main/res/values/strings.xml
PrebidMobile/PrebidMobile-admobAdapters/src/main/java/org/prebid/mobile/admob/PrebidRewardedAdapter.java
PrebidMobile/PrebidMobile-rendering/build.gradle
PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/sdk/PrebidRenderingSettings.java

Add display insterstitial examples and listeners. Closes #343.
Indicate the status of interstitial ads. Closes #344.
Fix listeners and confg ids for rewarded and interstitial. Closes #345.
Add open measurement version to code. Closes #346.
Add additional size to AdMob flexible banner. Closes #349.

AdMob fixes 

---

Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/AdTypesRepository.kt
Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/ads/inappadmob/InAppAdMobInterstitial.kt
Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/ads/inappmopub/InAppMoPubInterstitial.kt
Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/ads/inappmopub/InAppMoPubVideoInterstitial.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/InternalTestApplication.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/admob/AdMobNativeFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/mopub/MopubBannersWithInterstitialFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/mopub/MopubInterstitialFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/mopub/MopubNativeFragment.kt
Example/PrebidInternalTestApp/src/main/res/values/strings.xml

Use appropriate ad unit format for interstitial. Fix native ad crash. Correction in native ad requests. Closes #354, #356, #357.

AdMob corrections

---

Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/Util.java
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/utils/OpenRtbConfigs.kt
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/AdUnit.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/ContentObject.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/DataObject.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/RequestParams.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/TargetingParams.java
PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/bidding/display/MediationBaseAdUnit.java
PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/bidding/display/MediationNativeAdUnit.java
PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/bidding/parallel/BannerView.java
PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/bidding/parallel/BaseInterstitialAdUnit.java
PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/models/AdConfiguration.java
PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/models/HTMLCreative.java
PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/User.java
PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/networking/parameters/AppInfoParameterBuilder.java
PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilder.java
PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/networking/targeting/Targeting.java
PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/video/VideoCreative.java
PrebidMobile/PrebidMobile-rendering/src/main/java/org/prebid/mobile/rendering/views/base/BaseAdView.java
PrebidMobile/PrebidMobile-rendering/src/test/java/org/prebid/mobile/rendering/networking/parameters/AppInfoParameterBuilderTest.java
PrebidMobile/PrebidMobile-rendering/src/test/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilderTest.java
PrebidMobile/src/test/java/org/prebid/mobile/AdUnitContentTest.java
PrebidMobile/src/test/java/org/prebid/mobile/ContentObjectTest.java
PrebidMobile/src/test/java/org/prebid/mobile/JsonUserDataTest.java
PrebidMobile/src/test/java/org/prebid/mobile/PrebidNativeNativeTest.java
PrebidMobile/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
PrebidMobile/src/test/java/org/prebid/mobile/RequestParamsTest.java
PrebidMobile/src/test/java/org/prebid/mobile/TargetingParamsTest.java

Add ability to put user data objects. Closes #358.

Support for Seller-Defined Audiences for First Party Data

---

Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/ppm/PpmInterstitialCloseButtonAreaFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/utils/DemoItemProvider.kt
Example/PrebidInternalTestApp/src/main/res/navigation/bidding_navigation.xml
Example/PrebidInternalTestApp/src/main/res/values/strings.xml
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/parallel/BaseInterstitialAdUnit.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/interstitial/AdBaseDialog.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/interstitial/InterstitialLayoutConfigurator.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/models/InterstitialDisplayPropertiesInternal.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/utils/helpers/Utils.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/units/configuration/AdUnitConfiguration.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/units/configuration/Position.java
PrebidMobile/PrebidMobile-core/src/main/res/layout/lyt_close.xml
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/utils/helpers/UtilsTest.java
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/views/video/VideoDialogTest.java

Add close button area and position properties

---

Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/utils/DemoItemProvider.kt
Example/PrebidInternalTestApp/src/main/res/values/strings.xml
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/data/bid/Bid.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/data/bid/BidResponse.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/loader/BidLoader.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/MobileSdkPassThrough.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/units/configuration/Position.java
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/bidding/data/bid/BidResponseTest.java
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/MobileSdkPassThroughTest.java
PrebidMobile/PrebidMobile-core/src/test/resources/BidResponseTest/mobile_sdk_pass_through.json
scripts/testPrebidMobile.sh

Add parser for the "prebidmobilesdk" pass through. Automatically replace user ad unit configuration with ones from the bid. Values from the winning bid must have higher priority. Closes #422.

Rendering controls settings from bid responses

---

PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/utils/helpers/ExternalViewerUtils.java

to fix android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag.

add FLAG_ACTIVITY_NEW_TASK for external browser

---

Example/PrebidDemoJava/src/main/java/org/prebid/mobile/javademo/CustomApplication.java
Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/CustomApplication.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/AdFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/InternalTestApplication.kt
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/exceptions/InitError.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/mediation/MediationBaseAdUnit.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/rendering/BannerView.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/rendering/BaseInterstitialAdUnit.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/listeners/SdkInitializationListener.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/sdk/ManagersResolver.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/sdk/SdkInitializer.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/sdk/StatusRequester.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/sdk/deviceData/listeners/SdkInitListener.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/views/base/BaseAdView.java
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/sdk/PrebidMobileTest.java
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/sdk/SdkInitializerTest.java
PrebidMobile/PrebidMobile-maxAdapters/src/main/java/com/applovin/mediation/adapters/PrebidMaxMediationAdapter.java
PrebidMobile/tests.gradle
scripts/testPrebidMobile.sh
tools/drprebid/src/main/java/org/prebid/mobile/drprebid/DrPrebidApplication.java
tools/drprebid/src/main/java/org/prebid/mobile/drprebid/validation/RealTimeDemandTest.java
tools/drprebid/src/main/java/org/prebid/mobile/drprebid/validation/SdkTest.java

Save application context even if activity context was placed. Add request to the status endpoint when init SDK. Check if the previous init context is null when calling init SDK, to have the ability to make reinitialization. Replace all setApplicationContext SDK calls with new ones. Closes #447.
Other: Move all initialization methods to SdkInitializer. Refactor PrebidMobile. Create a new SDK initialization listener. Deprecate the LogLevel field and create a setter.

Initialization improvements

---

Example/PrebidInternalTestApp/src/main/AndroidManifest.xml
PrebidMobile/PrebidMobile-core/src/main/AndroidManifest.xml
PrebidMobile/PrebidMobile-gamEventHandlers/src/main/AndroidManifest.xml

Make permissions ACCESS_FINE_LOCATION and WRITE_EXTERNAL_STORAGE optional for publishers.

Remove optional permissions from SDK

---

PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/parameters/GeoLocationParameterBuilder.java

Populate country property from telephonyManager-locale-reverseGeocoding

Populate device.geo.country property

---

PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/BaseNetworkTask.java

There is an issue when the `vastadtaguri` element in the VAST XML contains an URL with query params.

fix(Render): Add get query params on url request builder

---

PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/parser/AdResponseParserVast.java
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/parser/AdResponseParserVastTest.java

We found a NPE crash related to empty VAST XML like this:
`<VAST version="2.0"></VAST>`

fix(Render): fix NPE in ad response parser vast on get vast url method

---

PrebidMobile/PrebidMobile-core/build.gradle
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/loading/VastParserExtractor.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/utils/helpers/Utils.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/video/ExoPlayerView.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/video/VideoCreative.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/views/AdViewManager.java
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/utils/url/action/MraidInternalBrowserActionTest.java
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/video/ExoPlayerViewTest.java
build.gradle

Resolve conflicts. Returned consistent behavior with iOS (according to [issue](https://github.com/prebid/prebid-mobile-android/issues/462))
* Update exoplayer to version 2.15.1 and replace deprecated code
* Fix internal browser action test
* fix(Render): Add get query params on url request builder
* fix(Render): replace vast regex validator to include other valid formats and unified validation criteria on vast parser extractor
* fix(Render): fix exo player issue by changing video uri builder
* fix(Render): close interstitial video only when it is an end card
* fix(render): show call to action on rewarded video
* fix(Render): fix NPE in ad response parser vast on get vast url method
* Update release version to 2.0.2.1
Co-authored-by: German Gonzalez <german.gonzalez@etermax.com> …

Update exoplayer to version 2.15.1 and replace deprecated code (#482)

---

Example/PrebidDemoJava/src/main/AndroidManifest.xml

The Java demo app used the old format of the GAD application id. So after an automatic GAM update, the app throws a runtime exception. 
```
java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider.
```

Replace GAD application id with new format

---

Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/gam/original/GamOriginalInterstitialFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/gam/original/GamOriginalOutstreamFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/gam/original/GamOriginalRewardedVideoFragment.kt
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/ImpTest.java
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/imps/VideoTest.java
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilderTest.java

Add unit tests for Video parameters. Closes #552.

Remove configuration properties from examples in the Internal app

---

Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/HeaderBiddingFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/HeaderBiddingViewModel.kt
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/sdk/SdkInitializer.java
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/PrebidMobileTest.java
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/api/rendering/DisplayViewTest.java
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/api/rendering/InterstitialAdUnitTest.java
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/api/rendering/RewardedAdUnitTest.java

This is to disable the ability to register plugin renderers from PrebidMobile class. Anyway internal classes can and must still use the internal singleton register, since prebid render its ads now under the new rendering interfaces

Disable plugin register to be used from PrebidMobile class

---

PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/NativeAsset.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/NativeDataAsset.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/NativeImageAsset.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/NativeTitleAsset.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/Native.java
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/NativeAssetTest.java

* There were changes made for assigning Native asset ids in [this PR](https://github.com/prebid/prebid-mobile-android/pull/273/files).
* But after some refactoring, these changes were reverted, I am not sure why.
* I have made this fix, please feel free to share your feedback / approve the PR.
* This is a solution to issue #640 reported on github.

MS-5342 Fix for Prebid Asset id missing even after enabling assignNativeAssetID

---

PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/ClickTracker.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/ClickTrackerListener.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidNativeAd.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/SharedNetworkManager.java

Motivation: Feature request https://github.com/prebid/prebid-mobile-android/issues/649
Currently, the Prebid Mobile SDK is not making use of the link.clicktrackers of the standard OpenRTB protocol. This pull request is to implement that feature.
Whenever a native ad is tapped (or, "clicked"), it should send HTTP GET requests to all the urls in the link.clicktrackers array.
(I messed up the previous Pull Request 🙈)

clicktrackers implementation for native ads

---

Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/activities/ads/inapp/InAppNativeActivity.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/ppm/PpmNativeFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/ppm/PpmNativeLinksFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/utils/BaseEvents.kt
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/CacheManager.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/ClickTracker.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/ImpressionTracker.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidNativeAd.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/VisibilityDetector.java

Improve memory management for Native ads

---

Example/PrebidDemoJava/src/main/java/org/prebid/mobile/javademo/activities/ads/gam/original/GamOriginalApiNativeInApp.java
Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/activities/ads/gam/original/GamOriginalApiNativeInAppActivity.kt
Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/activities/ads/gam/rendering/GamRenderingApiNativeActivity.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/gam/original/GamOriginalNativeInAppFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/ppm/PpmNativeFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/ppm/PpmNativeLinksFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/utils/adapters/NativeFeedAdapter.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/utils/adapters/NativeGamFeedAdapter.kt
PrebidMobile/PrebidMobile-admobAdapters/src/main/java/org/prebid/mobile/admob/PrebidNativeAdMapper.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidNativeAd.java
PrebidMobile/PrebidMobile-maxAdapters/src/main/java/com/applovin/mediation/adapters/prebid/PrebidMaxNativeAd.java

Rewrite deprecated registerView() in test examples

---

PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java
scripts/Maven/PrebidMobile-admobAdapters-pom.xml
scripts/Maven/PrebidMobile-gamEventHandlers-pom.xml

Currently CI fails due to
```
Google Ad SDK was updated to 22.3.0! Please test Prebid SDK with the new version, resolve compilation problems, rewrite deprecated code. After testing you must update PrebidMobile.TESTED_GOOGLE_SDK_VERSIONand also must update version in publishing XML files (scripts/Maven/*.xml. expected:<22.3.[0]> but was:<22.2.[0]>
Expected :22.3.0
Actual   :22.2.0
```
No deprecation related to previous version or breaking changes
https://developers.google.com/ad-manager/mobile-ads-sdk/android/rel-notes

Update Google Ad SDK Version to 22.3.0

---

PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/data/bid/Prebid.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/models/openrtb/BidRequest.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/PluginRendererList.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilder.java
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/PluginRendererListTest.java
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilderTest.java

This pull request is to solve the following issue:
[This pull request](https://github.com/prebid/prebid-mobile-android/pull/648) intended to insert renderers on the following node path from the bid request:
`.ext.prebid.sdk.renderers`
But the implementation did not match the expectation [as you can see here](https://github.com/prebid/prebid-mobile-android/blob/0f5a3d8a9cd36b095da96f9ee0e29007a17e849b/PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilder.java#L438), so the current state is
`.ext.sdk.renderers`

Fix renderers key node on bid request

---

Example/PrebidDemoJava/build.gradle
Example/PrebidDemoKotlin/build.gradle
Example/PrebidDemoKotlin/src/androidTest/java/org/prebid/mobile/prebidkotlindemo/ui/VideoAdsTest.kt
Example/PrebidInternalTestApp/build.gradle
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java
build.gradle
scripts/Maven/PrebidMobile-admobAdapters-pom.xml
scripts/Maven/PrebidMobile-gamEventHandlers-pom.xml

Currently `PrebidInternalTestApp` project run is failing due to the error below.
This sub-dependency `androidx.privacysandbox.ads:ads-adservices*` requires to compile against version `33`, current value on this project is `32`. As consequence Kotlin plugin needed to be update to >= `1.8`.
I was not able to track which commit brought this breaking change, so apparently we have a dependency that was updated without version increment on the maven repo.
⚠️ Plus Google SDK version was updated, so this is blocking the CI, so I am taking the chance to update it as well.
to-do
---
Error
---
```
2 issues were found when checking AAR metadata:
1.  Dependency 'androidx.privacysandbox.ads:ads-adservices-java:1.0.0-beta05' requires libraries and applications that
depend on it to compile against …
```

Update compile and target version to 33; Update Kotlin plugin to 1.8.22; Update Google SDK version to 22.4.0

---

Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/activities/ads/admob/AdMobVideoRewardedActivity.kt
Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/activities/ads/applovin/AppLovinMaxVideoRewardedActivity.kt
Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/activities/ads/gam/rendering/GamRenderingApiVideoRewardedActivity.kt
Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/activities/ads/inapp/InAppVideoRewardedActivity.kt

After implementing the rewarded ad unit functionality, our test app's rewarded examples wait for the close button to trigger the default timeout, which is 120 seconds. To complete smoke tests faster, we replaced the rewarded config IDs.

Fix smoke tests 

---

Example/PrebidInternalTestApp/src/main/AndroidManifest.xml
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/InternalTestApplication.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/testing/PrebidUniversalCreativeTestingFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/testing/PrebidUniversalCreativeTestingGamFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/utils/DemoItemProvider.kt
Example/PrebidInternalTestApp/src/main/res/layout/fragment_empty.xml
Example/PrebidInternalTestApp/src/main/res/layout/fragment_puc_testing.xml
Example/PrebidInternalTestApp/src/main/res/layout/fragment_puc_testing_gam.xml
Example/PrebidInternalTestApp/src/main/res/navigation/bidding_navigation.xml
Example/PrebidInternalTestApp/src/main/res/values/strings.xml

We need a way to run PUC Karma tests inside the Android environment. So for this, we added new test cases to the internal test app:
- SDK Testing: Prebid Universal Creative (WebView) - for testing with a simple WebView browser. 
- SDK Testing: Prebid Universal Creative (GAM) - for testing inside GAM wrapper. 
[Documentation for testing PUC](https://docs.google.com/document/d/1VGpxo0q5XJo7Ff0i1Zkoho7boJGk_mtKBoOCZOnOLig/edit?usp=sharing).

Introduce test cases for PUC

---

PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilder.java
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilderTest.java

The current implementation sends a device size as the desired size when no other ad sizes are provided. We removed the device size sending functionality.  
[Issue](https://github.com/prebid/prebid-mobile-ios/issues/391).

Do not use device size if there is no ad size

---

PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidNativeAd.java
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/PrebidNativeAdTest.java

[Issue](https://github.com/prebid/prebid-mobile-android/issues/818).

Public click URL for native ad

---

PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidEventDelegate.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/data/bid/BidResponse.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/bidding/loader/BidLoader.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/modelcontrollers/Requester.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/urlBuilder/URLComponents.java
PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/bidding/loader/BidLoaderTest.java

[Original issue](https://github.com/prebid/prebid-mobile-ios/pull/1035).

Introduce event delegate

---

PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/AdUnit.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/NativeAdUnit.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/loading/CreativeFactory.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/models/CreativeModel.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/models/CreativeModelMakerBids.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/models/CreativeModelsMakerVast.java
PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/video/VideoCreative.java

[Issue](https://github.com/prebid/prebid-mobile-ios/issues/1059).

Track nurl and burl

---

Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/AdFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/admob/AdMobBannerFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/admob/AdMobInterstitialFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/admob/AdMobNativeFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/admob/AdMobRewardedFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/base/BaseBidInterstitialFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/base/BaseBidRewardedFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/gam/original/GamOriginalBannerFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/gam/original/GamOriginalMultiformatBannerVideoNativeFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/gam/original/GamOriginalMultiformatBannerVideoNativeStylesFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/gam/original/GamOriginalNativeBannerFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/gam/original/GamOriginalOutstreamFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/gam/original/GamOriginalOutstreamNewApiFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/gam/rendering/GamBannerFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/gam/rendering/GamOutstreamFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/max/MaxBannerFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/max/MaxInterstitialFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/max/MaxNativeFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/max/MaxRewardedFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/pluginrenderer/PpmBannerPluginEventListenerFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/pluginrenderer/PpmBannerPluginRendererFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/ppm/PpmBannerFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/ppm/PpmNativeFragment.kt
Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/ppm/PpmVideoFragment.kt

In some cases in the internal test app crashes when there is ad failed callback (f.e. when network is disabled). 
```
E  FATAL EXCEPTION: main
Process: org.prebid.mobile.renderingtestapp, PID: 21150
kotlin.UninitializedPropertyAccessException: lateinit property events has not been initialized
at org.prebid.mobile.renderingtestapp.plugplay.bidding.ppm.PpmVideoFragment.getEvents(PpmVideoFragment.kt:45)
at org.prebid.mobile.renderingtestapp.plugplay.bidding.ppm.PpmVideoFragment.onAdFailed(PpmVideoFragment.kt:89)
at org.prebid.mobile.api.rendering.BannerView.notifyErrorListener(BannerView.java:521)
at org.prebid.mobile.api.rendering.BannerView.-$$Nest$mnotifyErrorListener(Unknown Source:0)
at org.prebid.mobile.api.rendering.BannerView$4.onPrebidSdkWin(BannerView.java:191)
at …
```

Fix for internal test app crashes
